language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-sinatra' ]; then cd .. && eval "mv $currentfolder generator-sinatra" && cd generator-sinatra; fi

